# Generated by Django 2.1.7 on 2019-04-06 15:46

from django.db import migrations, models
import tim_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, validators=[tim_app.validators.ValidateMinLength(3)])),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Business', 'Business'), ('Misc.', 'Misc.')], max_length=256)),
                ('message', models.TextField(validators=[tim_app.validators.ValidateMinLength(20)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
