# Generated by Django 2.1.7 on 2019-04-06 20:12

from django.db import migrations, models
import tim_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('bio', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(validators=[tim_app.validators.ValidateMinLength(5)]),
        ),
    ]
